##BUDS_SERVER='10.8.136.68'
##BUDS_USER='Adapuser1'
##BUDS_PASSWORD='AcEla901'
##BUDS=['10.8.136.68','Adapuser1', 'AcEla901']
SERV2_VIEWS_EXIST=['CUSRTA_PV_SERV2_CELLGP_BH','CUSRTA_PV_SERV2_CELLGP_HOUR','CUSRTA_PV_SERV2_CELLGP_DAY','CUSRTA_PV_SERV2_CELLGP_WEEK','CUSRTA_PV_SERV2_CELLGP_WEEKBH',
                   'CUSRTA_PV_SERV2_NETWORK_BH','CUSRTA_PV_SERV2_NETWORK_HOUR','CUSRTA_PV_SERV2_NETWORK_DAY','CUSRTA_PV_SERV2_NETWORK_WEEK','CUSRTA_PV_SERV2_NETWORK_WEEKBH',
                   'CUSRTA_PV_SERV2_REGION_BH','CUSRTA_PV_SERV2_REGION_HOUR','CUSRTA_PV_SERV2_REGION_DAY','CUSRTA_PV_SERV2_REGION_WEEK','CUSRTA_PV_SERV2_REGION_WEEKBH',
                   'CUSRTA_PV_SERV2_SUBREG_BH','CUSRTA_PV_SERV2_SUBREG_HOUR','CUSRTA_PV_SERV2_SUBREG_DAY','CUSRTA_PV_SERV2_SUBREG_WEEK','CUSRTA_PV_SERV2_SUBREG_WEEKBH',
                   'CUSRTA_PV_SERV2_WCEL_BH','CUSRTA_PV_SERV2_WCEL_HOUR','CUSRTA_PV_SERV2_WCEL_DAY','CUSRTA_PV_SERV2_WCEL_WEEK','CUSRTA_PV_SERV2_WCEL_WEEKBH',
                   'CUSRTA_PV_SERV2_WCEL1_BH','CUSRTA_PV_SERV2_WCEL1_HOUR','CUSRTA_PV_SERV2_WCEL1_DAY','CUSRTA_PV_SERV2_WCEL1_WEEK','CUSRTA_PV_SERV2_WCEL1_WEEKBH',
                   'CUSRTA_PV_SERV2_RNC_BH','CUSRTA_PV_SERV2_RNC_HOUR','CUSRTA_PV_SERV2_RNC_DAY','CUSRTA_PV_SERV2_RNC_WEEK','CUSRTA_PV_SERV2_RNC_WEEKBH']
SERV2_VIEWS_NONEXIST=['CUSRTA_PV_SERV2_CELLGP_BHQ','CUSRTA_PV_SERV2_CELLGP_HOURQ','CUSRTA_PV_SERV2_CELLGP_WKBHQ','CUSRTA_PV_SERV2_CELLGP_PEAKBH','CUSRTA_PV_SERV2_CELLGP_TTLBH','CUSRTA_PV_SERV2_CELLGP_WTTLBH',
                      'CUSRTA_PV_SERV2_NETWORK_BHQ','CUSRTA_PV_SERV2_NETWORK_HOURQ','CUSRTA_PV_SERV2_NETWORK_WKBHQ','CUSRTA_PV_SERV2_NETWORK_PEAKBH','CUSRTA_PV_SERV2_NETWORK_TTLBH','CUSRTA_PV_SERV2_NETWORK_WTTLBH',
                      'CUSRTA_PV_SERV2_REGION_BHQ','CUSRTA_PV_SERV2_REGION_HOURQ','CUSRTA_PV_SERV2_REGION_WKBHQ','CUSRTA_PV_SERV2_REGION_PEAKBH','CUSRTA_PV_SERV2_REGION_TTLBH','CUSRTA_PV_SERV2_REGION_WTTLBH',
                      'CUSRTA_PV_SERV2_SUBREG_BHQ','CUSRTA_PV_SERV2_SUBREG_HOURQ','CUSRTA_PV_SERV2_SUBREG_WKBHQ','CUSRTA_PV_SERV2_SUBREG_PEAKBH','CUSRTA_PV_SERV2_SUBREG_TTLBH','CUSRTA_PV_SERV2_SUBREG_WTTLBH',
                      'CUSRTA_PV_SERV2_WCEL_BHQ','CUSRTA_PV_SERV2_WCEL_HOURQ','CUSRTA_PV_SERV2_WCEL_WKBHQ','CUSRTA_PV_SERV2_WCEL_PEAKBH','CUSRTA_PV_SERV2_WCEL_TTLBH','CUSRTA_PV_SERV2_WCEL_WTTLBH',
                      'CUSRTA_PV_SERV2_WCEL1_BHQ','CUSRTA_PV_SERV2_WCEL1_HOURQ','CUSRTA_PV_SERV2_WCEL1_WKBHQ','CUSRTA_PV_SERV2_WCEL1_PEAKBH','CUSRTA_PV_SERV2_WCEL1_TTLBH','CUSRTA_PV_SERV2_WCEL1_WTTLBH',
                      'CUSRTA_PV_SERV2_RNC_BHQ','CUSRTA_PV_SERV2_RNC_HOURQ','CUSRTA_PV_SERV2_RNC_WKBHQ','CUSRTA_PV_SERV2_RNC_PEAKBH','CUSRTA_PV_SERV2_RNC_TTLBH','CUSRTA_PV_SERV2_RNC_WTTLBH']
TPBHQ_VIEWS_EXIST=['CUSRTA_PV_TPBHQ_WCEL_HOURQ','CUSRTA_PV_TPBHQ_WCEL_BHQ','CUSRTA_PV_TPBHQ_WCEL_WKBHQ']
TPBHQ_VIEWS_NONEXIST=['CUSRTA_PV_TPBHQ_WCEL_BH','CUSRTA_PV_TPBHQ_WCEL_DAY','CUSRTA_PV_TPBHQ_WCEL_PEAKBH','CUSRTA_PV_TPBHQ_WCEL_TTLBH','CUSRTA_PV_TPBHQ_WCEL_WTTLBH','CUSRTA_PV_TPBHQ_WCEL_WEEK','CUSRTA_PV_TPBHQ_WCEL_WEEKBH']
POFF_VIEWS_EXIST=['CUSRTA_PV_POFF_WCEL_HOUR','CUSRTA_PV_POFF_WCEL_HOURQ','CUSRTA_PV_POFF_WCEL_BHQ','CUSRTA_PV_POFF_WCEL_BH','CUSRTA_PV_POFF_WCEL_DAY',
                   'CUSRTA_PV_POFF_RNC_HOUR','CUSRTA_PV_POFF_RNC_HOURQ','CUSRTA_PV_POFF_RNC_BHQ','CUSRTA_PV_POFF_RNC_BH','CUSRTA_PV_POFF_RNC_DAY']
POFF_VIEWS_NONEXIST=['CUSRTA_PV_POFF_WCEL_PEAKBH','CUSRTA_PV_POFF_WCEL_TTLBH','CUSRTA_PV_POFF_WCEL_WTTLBH','CUSRTA_PV_POFF_WCEL_WEEKBH','CUSRTA_PV_POFF_WCEL_WEEK','CUSRTA_PV_POFF_WCEL_WKBHQ',
                     'CUSRTA_PV_POFF_RNC_PEAKBH','CUSRTA_PV_POFF_RNC_TTLBH','CUSRTA_PV_POFF_RNC_WTTLBH','CUSRTA_PV_POFF_RNC_WEEKBH','CUSRTA_PV_POFF_RNC_WEEK','CUSRTA_PV_POFF_RNC_WKBHQ']
QPBH_VIEWS_EXIST=['CUSRTA_PV_QPBH_WCEL_HOURQ','CUSRTA_PV_QPBH_WCEL_BHQ','CUSRTA_PV_QPBH_WCEL_WKBHQ']
QPBH_VIEWS_NONEXIST=['CUSRTA_PV_QPBH_WCEL_BH','CUSRTA_PV_QPBH_WCEL_DAY','CUSRTA_PV_QPBH_WCEL_PEAKBH','CUSRTA_PV_QPBH_WCEL_TTLBH','CUSRTA_PV_QPBH_WCEL_WEEK','CUSRTA_PV_QPBH_WCEL_WEEKBH','CUSRTA_PV_QPBH_WCEL_WTTLBH']
QPSBH_VIEWS_EXIST=['CUSRTA_PV_QPSBH_WCEL_HOUR','CUSRTA_PV_QPSBH_WCEL_HOURQ','CUSRTA_PV_QPSBH_WCEL_BHQ','CUSRTA_PV_QPSBH_WCEL_WKBHQ','CUSRTA_PV_QPSBH_WCEL_DAY','CUSRTA_PV_QPSBH_WCEL_WEEK']
QPSBH_VIEWS_NONEXIST=['CUSRTA_PV_QPSBH_WCEL_BH','CUSRTA_PV_QPSBH_WCEL_PEAKBH','CUSRTA_PV_QPSBH_WCEL_TTLBH','CUSRTA_PV_QPSBH_WCEL_WEEKBH','CUSRTA_PV_QPSBH_WCEL_WTTLBH']
##QPBHSBH_VIEWS_EXIST=['CUSRTA_PV_QPBHSBH_WCEL_HOURQ','CUSRTA_PV_QPBHSBH_WCEL_BHQ','CUSRTA_PV_QPBHSBH_WCEL_WKBHQ']
##QPBHSBH_VIEWS_NONEXIST=['CUSRTA_PV_QPBHSBH_WCEL_HOUR','CUSRTA_PV_QPBHSBH_WCEL_DAY','CUSRTA_PV_QPBHSBH_WCEL_WEEK','CUSRTA_PV_QPBHSBH_WCEL_BH','CUSRTA_PV_QPBHSBH_WCEL_PEAKBH','CUSRTA_PV_QPBHSBH_WCEL_TTLBH','CUSRTA_PV_QPBHSBH_WCEL_WEEKBH','CUSRTA_PV_QPBHSBH_WCEL_WTTLBH']
FMING_VIEWS_EXIST=['CUSRTA_PV_FMING_WCEL_PEAKBH','CUSRTA_PV_FMING_RNC_PEAKBH']
FMING_VIEWS_NONEXIST=['CUSRTA_PV_FMING_WCEL_HOUR','CUSRTA_PV_FMING_WCEL_BH','CUSRTA_PV_FMING_WCEL_DAY','CUSRTA_PV_FMING_WCEL_WEEK','CUSRTA_PV_FMING_WCEL_WEEKBH','CUSRTA_PV_FMING_WCEL_BHQ','CUSRTA_PV_FMING_WCEL_HOURQ','CUSRTA_PV_FMING_WCEL_WKBHQ','CUSRTA_PV_FMING_WCEL_TTLBH','CUSRTA_PV_FMING_WCEL_WTTLBH',
                      'CUSRTA_PV_FMING_RNC_HOUR','CUSRTA_PV_FMING_RNC_BH','CUSRTA_PV_FMING_RNC_DAY','CUSRTA_PV_FMING_RNC_WEEK','CUSRTA_PV_FMING_RNC_WEEKBH','CUSRTA_PV_FMING_RNC_BHQ','CUSRTA_PV_FMING_RNC_HOURQ','CUSRTA_PV_FMING_RNC_WKBHQ','CUSRTA_PV_FMING_RNC_TTLBH','CUSRTA_PV_FMING_RNC_WTTLBH']
FMOFF_VIEWS_EXIST=['CUSRTA_PV_FMOFF_WCEL_PEAKBH','CUSRTA_PV_FMOFF_WCEL_BH','CUSRTA_PV_FMOFF_WCEL_DAY','CUSRTA_PV_FMOFF_WCEL_WEEK','CUSRTA_PV_FMOFF_WCEL_WEEKBH',
                   'CUSRTA_PV_FMOFF_RNC_PEAKBH','CUSRTA_PV_FMOFF_RNC_BH','CUSRTA_PV_FMOFF_RNC_DAY','CUSRTA_PV_FMOFF_RNC_WEEK','CUSRTA_PV_FMOFF_RNC_WEEKBH']
FMOFF_VIEWS_NONEXIST=['CUSRTA_PV_FMOFF_WCEL_HOUR','CUSRTA_PV_FMOFF_WCEL_BHQ','CUSRTA_PV_FMOFF_WCEL_HOURQ','CUSRTA_PV_FMOFF_WCEL_WKBHQ','CUSRTA_PV_FMOFF_WCEL_TTLBH','CUSRTA_PV_FMOFF_WCEL_WTTLBH',
                      'CUSRTA_PV_FMOFF_RNC_HOUR','CUSRTA_PV_FMOFF_RNC_BHQ','CUSRTA_PV_FMOFF_RNC_HOURQ','CUSRTA_PV_FMOFF_RNC_WKBHQ','CUSRTA_PV_FMOFF_RNC_TTLBH','CUSRTA_PV_FMOFF_RNC_WTTLBH']
FMBH_VIEWS_EXIST=['CUSRTA_PV_FMBH_WCEL_PEAKBH','CUSRTA_PV_FMBH_RNC_PEAKBH']
FMBH_VIEWS_NONEXIST=['CUSRTA_PV_FMBH_WCEL_HOUR','CUSRTA_PV_FMBH_WCEL_BH','CUSRTA_PV_FMBH_WCEL_DAY','CUSRTA_PV_FMBH_WCEL_WEEK','CUSRTA_PV_FMBH_WCEL_WEEKBH','CUSRTA_PV_FMBH_WCEL_BHQ','CUSRTA_PV_FMBH_WCEL_HOURQ','CUSRTA_PV_FMBH_WCEL_WKBHQ','CUSRTA_PV_FMBH_WCEL_MNBHQ','CUSRTA_PV_FMBH_WCEL_TTLBH','CUSRTA_PV_FMBH_WCEL_WTTLBH','CUSRTA_PV_FMBH_WCEL_MTTLBH','CUSRTA_PV_FMBH_WCEL_MONTH','CUSRTA_PV_FMBH_WCEL_MONBH',
                      'CUSRTA_PV_FMBH_RNC_HOUR','CUSRTA_PV_FMBH_RNC_BH','CUSRTA_PV_FMBH_RNC_DAY','CUSRTA_PV_FMBH_RNC_WEEK','CUSRTA_PV_FMBH_RNC_WEEKBH','CUSRTA_PV_FMBH_RNC_BHQ','CUSRTA_PV_FMBH_RNC_HOURQ','CUSRTA_PV_FMBH_RNC_WKBHQ','CUSRTA_PV_FMBH_RNC_MNBHQ','CUSRTA_PV_FMBH_RNC_TTLBH','CUSRTA_PV_FMBH_RNC_WTTLBH','CUSRTA_PV_FMBH_RNC_MTTLBH','CUSRTA_PV_FMBH_RNC_MONTH','CUSRTA_PV_FMBH_RNC_MONBH']
FMBHOFF_VIEWS_EXIST=['CUSRTA_PV_FMBHOFF_WCEL_PEAKBH','CUSRTA_PV_FMBHOFF_WCEL_BH','CUSRTA_PV_FMBHOFF_WCEL_WEEKBH','CUSRTA_PV_FMBHOFF_RNC_PEAKBH','CUSRTA_PV_FMBHOFF_RNC_BH','CUSRTA_PV_FMBHOFF_RNC_WEEKBH']
FMBHOFF_VIEWS_NONEXIST=['CUSRTA_PV_FMBHOFF_WCEL_HOUR','CUSRTA_PV_FMBHOFF_WCEL_DAY','CUSRTA_PV_FMBHOFF_WCEL_WEEK','CUSRTA_PV_FMBHOFF_WCEL_BHQ','CUSRTA_PV_FMBHOFF_WCEL_HOURQ','CUSRTA_PV_FMBHOFF_WCEL_WKBHQ','CUSRTA_PV_FMBHOFF_WCEL_TTLBH','CUSRTA_PV_FMBHOFF_WCEL_WTTLBH',
                        'CUSRTA_PV_FMBHOFF_RNC_HOUR','CUSRTA_PV_FMBHOFF_RNC_DAY','CUSRTA_PV_FMBHOFF_RNC_WEEK','CUSRTA_PV_FMBHOFF_RNC_BHQ','CUSRTA_PV_FMBHOFF_RNC_HOURQ','CUSRTA_PV_FMBHOFF_RNC_WKBHQ','CUSRTA_PV_FMBHOFF_RNC_TTLBH','CUSRTA_PV_FMBHOFF_RNC_WTTLBH']
FMSBH_VIEWS_EXIST=['CUSRTA_PV_FMSBH_WCEL_PEAKBH','CUSRTA_PV_FMSBH_WCEL_HOUR','CUSRTA_PV_FMSBH_WCEL_DAY','CUSRTA_PV_FMSBH_WCEL_WEEK',
                   'CUSRTA_PV_FMSBH_RNC_PEAKBH','CUSRTA_PV_FMSBH_RNC_HOUR','CUSRTA_PV_FMSBH_RNC_DAY','CUSRTA_PV_FMSBH_RNC_WEEK',]
FMSBH_VIEWS_NONEXIST=['CUSRTA_PV_FMSBH_WCEL_BH','CUSRTA_PV_FMSBH_WCEL_WEEKBH','CUSRTA_PV_FMSBH_WCEL_BHQ','CUSRTA_PV_FMSBH_WCEL_HOURQ','CUSRTA_PV_FMSBH_WCEL_WKBHQ','CUSRTA_PV_FMSBH_WCEL_TTLBH','CUSRTA_PV_FMSBH_WCEL_WTTLBH','CUSRTA_PV_FMSBH_WCEL_MONBH'
                      'CUSRTA_PV_FMSBH_RNC_BH','CUSRTA_PV_FMSBH_RNC_WEEKBH','CUSRTA_PV_FMSBH_RNC_BHQ','CUSRTA_PV_FMSBH_RNC_HOURQ','CUSRTA_PV_FMSBH_RNC_WKBHQ','CUSRTA_PV_FMSBH_RNC_TTLBH','CUSRTA_PV_FMSBH_RNC_WTTLBH','CUSRTA_PV_FMSBH_RNC_MONBH']
FMBHSBH_VIEWS_EXIST=['CUSRTA_PV_FMBHSBH_WCEL_PEAKBH','CUSRTA_PV_FMBHSBH_RNC_PEAKBH']
FMBHSBH_VIEWS_NONEXIST=['CUSRTA_PV_FMBHSBH_WCEL_BH','CUSRTA_PV_FMBHSBH_WCEL_WEEKBH','CUSRTA_PV_FMBHSBH_WCEL_DAY','CUSRTA_PV_FMBHSBH_WCEL_WEEK','CUSRTA_PV_FMBHSBH_WCEL_HOUR','CUSRTA_PV_FMBHSBH_WCEL_BHQ','CUSRTA_PV_FMBHSBH_WCEL_HOURQ','CUSRTA_PV_FMBHSBH_WCEL_WKBHQ','CUSRTA_PV_FMBHSBH_WCEL_TTLBH','CUSRTA_PV_FMBHSBH_WCEL_WTTLBH',
                        'CUSRTA_PV_FMBHSBH_RNC_BH','CUSRTA_PV_FMBHSBH_RNC_WEEKBH','CUSRTA_PV_FMBHSBH_RNC_DAY','CUSRTA_PV_FMBHSBH_RNC_WEEK','CUSRTA_PV_FMBHSBH_RNC_HOUR','CUSRTA_PV_FMBHSBH_RNC_BHQ','CUSRTA_PV_FMBHSBH_RNC_HOURQ','CUSRTA_PV_FMBHSBH_RNC_WKBHQ','CUSRTA_PV_FMBHSBH_RNC_TTLBH','CUSRTA_PV_FMBHSBH_RNC_WTTLBH']
TTL_VIEWS_EXIST=['CUSRTA_PV_TTL_WCEL_TTLBH','CUSRTA_PV_TTL_WCEL_WTTLBH',
                 'CUSRTA_PV_TTL_RNC_TTLBH','CUSRTA_PV_TTL_RNC_WTTLBH']
TTL_VIEWS_NONEXIST=['CUSRTA_PV_TTL_WCEL_HOUR','CUSRTA_PV_TTL_WCEL_DAY','CUSRTA_PV_TTL_WCEL_WEEK','CUSRTA_PV_TTL_WCEL_HOURQ','CUSRTA_PV_TTL_WCEL_BHQ','CUSRTA_PV_TTL_WCEL_WKBHQ','CUSRTA_PV_TTL_WCEL_PEAKBH','CUSRTA_PV_TTL_WCEL_BH','CUSRTA_PV_TTL_WCEL_WEEKBH',
                    'CUSRTA_PV_TTL_RNC_HOUR','CUSRTA_PV_TTL_RNC_DAY','CUSRTA_PV_TTL_RNC_WEEK','CUSRTA_PV_TTL_RNC_HOURQ','CUSRTA_PV_TTL_RNC_BHQ','CUSRTA_PV_TTL_RNC_WKBHQ','CUSRTA_PV_TTL_RNC_PEAKBH','CUSRTA_PV_TTL_RNC_BH','CUSRTA_PV_TTL_RNC_WEEKBH']
TTLOFF_VIEWS_EXIST=['CUSRTA_PV_TTLOFF_WCEL_BH','CUSRTA_PV_TTLOFF_WCEL_WEEKBH','CUSRTA_PV_TTLOFF_WCEL_TTLBH','CUSRTA_PV_TTLOFF_WCEL_WTTLBH',
                 'CUSRTA_PV_TTLOFF_RNC_BH','CUSRTA_PV_TTLOFF_RNC_WEEKBH','CUSRTA_PV_TTLOFF_RNC_TTLBH','CUSRTA_PV_TTLOFF_RNC_WTTLBH']
TTLOFF_VIEWS_NONEXIST=['CUSRTA_PV_TTLOFF_WCEL_HOURQ','CUSRTA_PV_TTLOFF_WCEL_BHQ','CUSRTA_PV_TTLOFF_WCEL_WKBHQ','CUSRTA_PV_TTLOFF_WCEL_PEAKBH','CUSRTA_PV_TTLOFF_WCEL_HOUR','CUSRTA_PV_TTLOFF_WCEL_DAY','CUSRTA_PV_TTLOFF_WCEL_WEEK',
                    'CUSRTA_PV_TTLOFF_RNC_HOURQ','CUSRTA_PV_TTLOFF_RNC_BHQ','CUSRTA_PV_TTLOFF_RNC_WKBHQ','CUSRTA_PV_TTLOFF_RNC_PEAKBH''CUSRTA_PV_TTLOFF_RNC_HOUR','CUSRTA_PV_TTLOFF_RNC_DAY','CUSRTA_PV_TTLOFF_RNC_WEEK']
TTLSBH_VIEWS_EXIST=['CUSRTA_PV_TTLSBH_WCEL_TTLBH','CUSRTA_PV_TTLSBH_WCEL_WTTLBH',
                 'CUSRTA_PV_TTLSBH_RNC_TTLBH','CUSRTA_PV_TTLSBH_RNC_WTTLBH']
TTLSBH_VIEWS_NONEXIST=['CUSRTA_PV_TTLSBH_WCEL_BH','CUSRTA_PV_TTLSBH_WCEL_WEEKBH','CUSRTA_PV_TTLSBH_WCEL_HOURQ','CUSRTA_PV_TTLSBH_WCEL_BHQ','CUSRTA_PV_TTLSBH_WCEL_WKBHQ','CUSRTA_PV_TTLSBH_WCEL_PEAKBH','CUSRTA_PV_TTLSBH_WCEL_HOUR','CUSRTA_PV_TTLSBH_WCEL_DAY','CUSRTA_PV_TTLSBH_WCEL_WEEK',
                    'CUSRTA_PV_TTLSBH_RNC_BH','CUSRTA_PV_TTLSBH_RNC_WEEKBH','CUSRTA_PV_TTLSBH_RNC_HOURQ','CUSRTA_PV_TTLSBH_RNC_BHQ','CUSRTA_PV_TTLSBH_RNC_WKBHQ','CUSRTA_PV_TTLSBH_RNC_PEAKBH''CUSRTA_PV_TTLSBH_RNC_HOUR','CUSRTA_PV_TTLSBH_RNC_DAY','CUSRTA_PV_TTLSBH_RNC_WEEK']
ECONE_VIEWS_EXIST=['CUSRTA_PV_ECONE_WCEL_HOUR','CUSRTA_PV_ECONE_WCEL_BH','CUSRTA_PV_ECONE_WCEL_DAY','CUSRTA_PV_ECONE_WCEL_WEEK','CUSRTA_PV_ECONE_WCEL_WEEKBH',
                   'CUSRTA_PV_ECONE_RNC_HOUR','CUSRTA_PV_ECONE_RNC_BH','CUSRTA_PV_ECONE_RNC_DAY','CUSRTA_PV_ECONE_RNC_WEEK','CUSRTA_PV_ECONE_RNC_WEEKBH']
ECONE_VIEWS_NONEXIST=['CUSRTA_PV_ECONE_WCEL_HOURQ','CUSRTA_PV_ECONE_WCEL_BHQ','CUSRTA_PV_ECONE_WCEL_WKBHQ','CUSRTA_PV_ECONE_WCEL_PEAKBH','CUSRTA_PV_ECONE_WCEL_TTLBH','CUSRTA_PV_ECONE_WCEL_WTTLBH',
                      'CUSRTA_PV_ECONE_RNC_HOURQ','CUSRTA_PV_ECONE_RNC_BHQ','CUSRTA_PV_ECONE_RNC_WKBHQ','CUSRTA_PV_ECONE_RNC_PEAKBH','CUSRTA_PV_ECONE_RNC_TTLBH','CUSRTA_PV_ECONE_RNC_WTTLBH']
ECTWO_VIEWS_EXIST=['CUSRTA_PV_ECTWO_WCEL_BH','CUSRTA_PV_ECTWO_WCEL_WEEKBH','CUSRTA_PV_ECTWO_RNC_BH','CUSRTA_PV_ECTWO_RNC_WEEKBH']
ECTWO_VIEWS_NONEXIST=['CUSRTA_PV_ECTWO_WCEL_HOUR','CUSRTA_PV_ECTWO_WCEL_DAY','CUSRTA_PV_ECTWO_WCEL_WEEK','CUSRTA_PV_ECTWO_WCEL_HOURQ','CUSRTA_PV_ECTWO_WCEL_BHQ','CUSRTA_PV_ECTWO_WCEL_WKBHQ','CUSRTA_PV_ECTWO_WCEL_PEAKBH','CUSRTA_PV_ECTWO_WCEL_TTLBH','CUSRTA_PV_ECTWO_WCEL_WTTLBH',
                      'CUSRTA_PV_ECTWO_RNC_DAY','CUSRTA_PV_ECTWO_RNC_WEEK','CUSRTA_PV_ECTWO_RNC_HOUR','CUSRTA_PV_ECTWO_RNC_HOURQ','CUSRTA_PV_ECTWO_RNC_BHQ','CUSRTA_PV_ECTWO_RNC_WKBHQ','CUSRTA_PV_ECTWO_RNC_PEAKBH','CUSRTA_PV_ECTWO_RNC_TTLBH','CUSRTA_PV_ECTWO_RNC_WTTLBH']
ECTHR_VIEWS_EXIST=['CUSRTA_PV_ECTHR_WCEL_BH','CUSRTA_PV_ECTHR_WCEL_WEEKBH','CUSRTA_PV_ECTHR_RNC_BH','CUSRTA_PV_ECTHR_RNC_WEEKBH']
ECTHR_VIEWS_NONEXIST=['CUSRTA_PV_ECTHR_WCEL_HOUR','CUSRTA_PV_ECTHR_WCEL_DAY','CUSRTA_PV_ECTHR_WCEL_WEEK','CUSRTA_PV_ECTHR_WCEL_HOURQ','CUSRTA_PV_ECTHR_WCEL_BHQ','CUSRTA_PV_ECTHR_WCEL_WKBHQ','CUSRTA_PV_ECTHR_WCEL_PEAKBH','CUSRTA_PV_ECTHR_WCEL_TTLBH','CUSRTA_PV_ECTHR_WCEL_WTTLBH',
                      'CUSRTA_PV_ECTHR_RNC_DAY','CUSRTA_PV_ECTHR_RNC_WEEK','CUSRTA_PV_ECTHR_RNC_HOUR','CUSRTA_PV_ECTHR_RNC_HOURQ','CUSRTA_PV_ECTHR_RNC_BHQ','CUSRTA_PV_ECTHR_RNC_WKBHQ','CUSRTA_PV_ECTHR_RNC_PEAKBH','CUSRTA_PV_ECTHR_RNC_TTLBH','CUSRTA_PV_ECTHR_RNC_WTTLBH']
EXTTL_VIEWS_EXIST=['CUSRTA_PV_EXTTL_CELLGP_TTLBH','CUSRTA_PV_EXTTL_CELLGP_WTTLBH','CUSRTA_PV_EXTTL_CELLGP_BH','CUSRTA_PV_EXTTL_CELLGP_WEEKBH',
                   'CUSRTA_PV_EXTTL_NETWORK_TTLBH','CUSRTA_PV_EXTTL_NETWORK_WTTLBH','CUSRTA_PV_EXTTL_NETWORK_BH','CUSRTA_PV_EXTTL_NETWORK_WEEKBH',
                   'CUSRTA_PV_EXTTL_REGION_TTLBH','CUSRTA_PV_EXTTL_REGION_WTTLBH','CUSRTA_PV_EXTTL_REGION_BH','CUSRTA_PV_EXTTL_REGION_WEEKBH',
                   'CUSRTA_PV_EXTTL_SUBREG_TTLBH','CUSRTA_PV_EXTTL_SUBREG_WTTLBH','CUSRTA_PV_EXTTL_SUBREG_BH','CUSRTA_PV_EXTTL_SUBREG_WEEKBH',
                   'CUSRTA_PV_EXTTL_WCEL_TTLBH','CUSRTA_PV_EXTTL_WCEL_WTTLBH','CUSRTA_PV_EXTTL_WCEL_BH','CUSRTA_PV_EXTTL_WCEL_WEEKBH',
                   'CUSRTA_PV_EXTTL_WCEL1_TTLBH','CUSRTA_PV_EXTTL_WCEL1_WTTLBH','CUSRTA_PV_EXTTL_WCEL1_BH','CUSRTA_PV_EXTTL_WCEL1_WEEKBH',
                   'CUSRTA_PV_EXTTL_RNC_TTLBH','CUSRTA_PV_EXTTL_RNC_WTTLBH','CUSRTA_PV_EXTTL_RNC_BH','CUSRTA_PV_EXTTL_RNC_WEEKBH']
EXTTL_VIEWS_NONEXIST=['CUSRTA_PV_EXTTL_CELLGP_BHQ','CUSRTA_PV_EXTTL_CELLGP_HOURQ','CUSRTA_PV_EXTTL_CELLGP_WKBHQ','CUSRTA_PV_EXTTL_CELLGP_PEAKBH','CUSRTA_PV_EXTTL_CELLGP_HOUR','CUSRTA_PV_EXTTL_CELLGP_DAY','CUSRTA_PV_EXTTL_CELLGP_WEEK',
                      'CUSRTA_PV_EXTTL_NETWORK_BHQ','CUSRTA_PV_EXTTL_NETWORK_HOURQ','CUSRTA_PV_EXTTL_NETWORK_WKBHQ','CUSRTA_PV_EXTTL_NETWORK_PEAKBH','CUSRTA_PV_EXTTL_NETWORK_HOUR','CUSRTA_PV_EXTTL_NETWORK_DAY','CUSRTA_PV_EXTTL_NETWORK_WEEK',
                      'CUSRTA_PV_EXTTL_REGION_BHQ','CUSRTA_PV_EXTTL_REGION_HOURQ','CUSRTA_PV_EXTTL_REGION_WKBHQ','CUSRTA_PV_EXTTL_REGION_PEAKBH','CUSRTA_PV_EXTTL_REGION_HOUR','CUSRTA_PV_EXTTL_REGION_DAY','CUSRTA_PV_EXTTL_REGION_WEEK',
                      'CUSRTA_PV_EXTTL_SUBREG_BHQ','CUSRTA_PV_EXTTL_SUBREG_HOURQ','CUSRTA_PV_EXTTL_SUBREG_WKBHQ','CUSRTA_PV_EXTTL_SUBREG_PEAKBH','CUSRTA_PV_EXTTL_SUBREG_HOUR','CUSRTA_PV_EXTTL_SUBREG_DAY','CUSRTA_PV_EXTTL_SUBREG_WEEK',
                      'CUSRTA_PV_EXTTL_WCEL_BHQ','CUSRTA_PV_EXTTL_WCEL_HOURQ','CUSRTA_PV_EXTTL_WCEL_WKBHQ','CUSRTA_PV_EXTTL_WCEL_PEAKBH','CUSRTA_PV_EXTTL_WCEL_HOUR','CUSRTA_PV_EXTTL_WCEL_DAY','CUSRTA_PV_EXTTL_WCEL_WEEK',
                      'CUSRTA_PV_EXTTL_WCEL1_BHQ','CUSRTA_PV_EXTTL_WCEL1_HOURQ','CUSRTA_PV_EXTTL_WCEL1_WKBHQ','CUSRTA_PV_EXTTL_WCEL1_PEAKBH','CUSRTA_PV_EXTTL_WCEL1_HOUR','CUSRTA_PV_EXTTL_WCEL1_DAY','CUSRTA_PV_EXTTL_WCEL1_WEEK',
                      'CUSRTA_PV_EXTTL_RNC_BHQ','CUSRTA_PV_EXTTL_RNC_HOURQ','CUSRTA_PV_EXTTL_RNC_WKBHQ','CUSRTA_PV_EXTTL_RNC_PEAKBH','CUSRTA_PV_EXTTL_RNC_HOUR','CUSRTA_PV_EXTTL_RNC_DAY','CUSRTA_PV_EXTTL_RNC_WEEK']
##QPBHOFF_VIEWS_EXIST=['CUSRTA_PV_QPBHOFF_WCEL_BH','CUSRTA_PV_QPBHOFF_WCEL_WEEKBH','CUSRTA_PV_QPBHOFF_WCEL_BHQ','CUSRTA_PV_QPBHOFF_WCEL_HOURQ','CUSRTA_PV_QPBHOFF_WCEL_WKBHQ',
##                     'CUSRTA_PV_QPBHOFF_RNC_BH','CUSRTA_PV_QPBHOFF_RNC_WEEKBH','CUSRTA_PV_QPBHOFF_RNC_BHQ','CUSRTA_PV_QPBHOFF_RNC_HOURQ','CUSRTA_PV_QPBHOFF_RNC_WKBHQ']
##QPBHOFF_VIEWS_NONEXIST=['CUSRTA_PV_QPBHOFF_WCEL_HOUR','CUSRTA_PV_QPBHOFF_WCEL_DAY','CUSRTA_PV_QPBHOFF_WCEL_WEEK','CUSRTA_PV_QPBHOFF_WCEL_PEAKBH','CUSRTA_PV_QPBHOFF_WCEL_TTLBH','CUSRTA_PV_QPBHOFF_WCEL_WTTLBH',
##                        'CUSRTA_PV_QPBHOFF_RNC_HOUR','CUSRTA_PV_QPBHOFF_RNC_DAY','CUSRTA_PV_QPBHOFF_RNC_WEEK','CUSRTA_PV_QPBHOFF_RNC_PEAKBH','CUSRTA_PV_QPBHOFF_RNC_TTLBH','CUSRTA_PV_QPBHOFF_RNC_WTTLBH']
UPUSE_VIEWS_EXIST=['CUSRTA_PV_UPUSE_WCEL_HOUR','CUSRTA_PV_UPUSE_WCEL_DAY','CUSRTA_PV_UPUSE_WCEL_WEEK','CUSRTA_PV_UPUSE_WCEL_BH','CUSRTA_PV_UPUSE_WCEL_WEEKBH','CUSRTA_PV_UPUSE_WCEL_PEAKBH',
                   'CUSRTA_PV_UPUSE_RNC_HOUR','CUSRTA_PV_UPUSE_RNC_DAY','CUSRTA_PV_UPUSE_RNC_WEEK','CUSRTA_PV_UPUSE_RNC_BH','CUSRTA_PV_UPUSE_RNC_WEEKBH','CUSRTA_PV_UPUSE_RNC_PEAKBH']
UPUSE_VIEWS_NONEXIST=['CUSRTA_PV_UPUSE_WCEL_HOURQ','CUSRTA_PV_UPUSE_WCEL_BHQ','CUSRTA_PV_UPUSE_WCEL_WKBHQ','CUSRTA_PV_UPUSE_WCEL_TTLBH','CUSRTA_PV_UPUSE_WCEL_WTTLBH',
                      'CUSRTA_PV_UPUSE_RNC_HOURQ','CUSRTA_PV_UPUSE_RNC_BHQ','CUSRTA_PV_UPUSE_RNC_WKBHQ','CUSRTA_PV_UPUSE_RNC_TTLBH','CUSRTA_PV_UPUSE_RNC_WTTLBH']
ECFIVE_VIEWS_EXIST=['CUSRTA_PV_ECFIVE_WCEL_HOUR','CUSRTA_PV_ECFIVE_WCEL_BH','CUSRTA_PV_ECFIVE_WCEL_DAY','CUSRTA_PV_ECFIVE_WCEL_WEEK','CUSRTA_PV_ECFIVE_WCEL_WEEKBH',
                   'CUSRTA_PV_ECFIVE_RNC_HOUR','CUSRTA_PV_ECFIVE_RNC_BH','CUSRTA_PV_ECFIVE_RNC_DAY','CUSRTA_PV_ECFIVE_RNC_WEEK','CUSRTA_PV_ECFIVE_RNC_WEEKBH']
ECFIVE_VIEWS_NONEXIST=['CUSRTA_PV_ECFIVE_WCEL_HOURQ','CUSRTA_PV_ECFIVE_WCEL_BHQ','CUSRTA_PV_ECFIVE_WCEL_WKBHQ','CUSRTA_PV_ECFIVE_WCEL_PEAKBH','CUSRTA_PV_ECFIVE_WCEL_TTLBH','CUSRTA_PV_ECFIVE_WCEL_WTTLBH',
                      'CUSRTA_PV_ECFIVE_RNC_HOURQ','CUSRTA_PV_ECFIVE_RNC_BHQ','CUSRTA_PV_ECFIVE_RNC_WKBHQ','CUSRTA_PV_ECFIVE_RNC_PEAKBH','CUSRTA_PV_ECFIVE_RNC_TTLBH','CUSRTA_PV_ECFIVE_RNC_WTTLBH']
ECFOUR_VIEWS_EXIST=['CUSRTA_PV_ECFOUR_WCEL_HOUR','CUSRTA_PV_ECFOUR_WCEL_BH','CUSRTA_PV_ECFOUR_WCEL_DAY','CUSRTA_PV_ECFOUR_WCEL_WEEK','CUSRTA_PV_ECFOUR_WCEL_WEEKBH',
                   'CUSRTA_PV_ECFOUR_RNC_HOUR','CUSRTA_PV_ECFOUR_RNC_BH','CUSRTA_PV_ECFOUR_RNC_DAY','CUSRTA_PV_ECFOUR_RNC_WEEK','CUSRTA_PV_ECFOUR_RNC_WEEKBH']
ECFOUR_VIEWS_NONEXIST=['CUSRTA_PV_ECFOUR_WCEL_HOURQ','CUSRTA_PV_ECFOUR_WCEL_BHQ','CUSRTA_PV_ECFOUR_WCEL_WKBHQ','CUSRTA_PV_ECFOUR_WCEL_PEAKBH','CUSRTA_PV_ECFOUR_WCEL_TTLBH','CUSRTA_PV_ECFOUR_WCEL_WTTLBH',
                      'CUSRTA_PV_ECFOUR_RNC_HOURQ','CUSRTA_PV_ECFOUR_RNC_BHQ','CUSRTA_PV_ECFOUR_RNC_WKBHQ','CUSRTA_PV_ECFOUR_RNC_PEAKBH','CUSRTA_PV_ECFOUR_RNC_TTLBH','CUSRTA_PV_ECFOUR_RNC_WTTLBH']
ECSIX_VIEWS_EXIST=['CUSRTA_PV_ECSIX_WCEL_BH','CUSRTA_PV_ECSIX_WCEL_WEEKBH',
                   'CUSRTA_PV_ECSIX_RNC_BH','CUSRTA_PV_ECSIX_RNC_WEEKBH']
ECSIX_VIEWS_NONEXIST=['CUSRTA_PV_ECSIX_WCEL_HOUR','CUSRTA_PV_ECSIX_WCEL_DAY','CUSRTA_PV_ECSIX_WCEL_WEEK','CUSRTA_PV_ECSIX_WCEL_HOURQ','CUSRTA_PV_ECSIX_WCEL_BHQ','CUSRTA_PV_ECSIX_WCEL_WKBHQ','CUSRTA_PV_ECSIX_WCEL_PEAKBH','CUSRTA_PV_ECSIX_WCEL_TTLBH','CUSRTA_PV_ECSIX_WCEL_WTTLBH',
                      'CUSRTA_PV_ECSIX_RNC_HOUR','CUSRTA_PV_ECSIX_RNC_DAY','CUSRTA_PV_ECSIX_RNC_WEEK','CUSRTA_PV_ECSIX_RNC_HOURQ','CUSRTA_PV_ECSIX_RNC_BHQ','CUSRTA_PV_ECSIX_RNC_WKBHQ','CUSRTA_PV_ECSIX_RNC_PEAKBH','CUSRTA_PV_ECSIX_RNC_TTLBH','CUSRTA_PV_ECSIX_RNC_WTTLBH']
CHECK_SYNONMS=['CUSRTA_PV_TPBHQ_WCEL_HOUR','CUSRTA_PV_QPBH_WCEL_HOUR','CUSRTA_PV_QPBHSBH_WCEL_HOUR','CUSRTA_PV_TTL_WCEL_BH','CUSRTA_PV_TTL_WCEL_WEEKBH','CUSRTA_PV_TTLSBH_WCEL_BH','CUSRTA_PV_TTLSBH_WCEL_WEEKBH']
#Used for New Standard Adaptation
##FCELLR_VIEWS_EXIST=['CUSAW1_PV_FCELLR_FWCEL_HOUR','CUSAW1_PV_FCELLR_FWCEL_DAY','CUSAW1_PV_FCELLR_FWCEL_BH',
##                    'CUSAW1_PV_FCELLR_FRNCU_HOUR','CUSAW1_PV_FCELLR_FRNCU_DAY','CUSAW1_PV_FCELLR_FRNCU_BH']
##FCELLR_VIEWS_NONEXIST=['CUSAW1_PV_FCELLR_FWCEL_HOURQ','CUSAW1_PV_FCELLR_FWCEL_BHQ','CUSAW1_PV_FCELLR_FWCEL_PEAKBH','CUSAW1_PV_FCELLR_FWCEL_TTLBH',
##                       'CUSAW1_PV_FCELLR_FRNCU_HOURQ','CUSAW1_PV_FCELLR_FRNCU_BHQ','CUSAW1_PV_FCELLR_FRNCU_PEAKBH','CUSAW1_PV_FCELLR_FRNCU_TTLBH'
##                       'CUSAW1_PV_FCELLR_MNC_HOUR','CUSAW1_PV_FCELLR_MNC_DAY','CUSAW1_PV_FCELLR_MNC_BH','CUSAW1_PV_FCELLR_MNC_HOURQ','CUSAW1_PV_FCELLR_MNC_BHQ','CUSAW1_PV_FCELLR_MNC_PEAKBH','CUSAW1_PV_FCELLR_MNC_TTLBH']
##HWRES_VIEWS_EXIST=['CUSAW1_PV_HWRES_FWCEL_HOUR','CUSAW1_PV_HWRES_FWCEL_HOURQ','CUSAW1_PV_HWRES_FWCEL_BHQ','CUSAW1_PV_HWRES_FWCEL_WKBHQ',
##                   'CUSAW1_PV_HWRES_FRNCU_HOUR','CUSAW1_PV_HWRES_FRNCU_HOURQ','CUSAW1_PV_HWRES_FRNCU_BHQ','CUSAW1_PV_HWRES_FRNCU_WKBHQ',
##                   'CUSAW1_PV_HWRES_MNC_HOUR','CUSAW1_PV_HWRES_MNC_HOURQ','CUSAW1_PV_HWRES_MNC_BHQ','CUSAW1_PV_HWRES_MNC_WKBHQ']
##HWRES_VIEWS_NONEXIST=['CUSAW1_PV_HWRES_FWCEL_DAY','CUSAW1_PV_HWRES_FWCEL_WEEK','CUSAW1_PV_HWRES_FWCEL_BH','CUSAW1_PV_HWRES_FWCEL_WEEKBH','CUSAW1_PV_HWRES_FWCEL_PEAKBH','CUSAW1_PV_HWRES_FWCEL_TTLBH','CUSAW1_PV_HWRES_FWCEL_WTTLBH',
##                      'CUSAW1_PV_HWRES_FRNCU_DAY','CUSAW1_PV_HWRES_FRNCU_WEEK','CUSAW1_PV_HWRES_FRNCU_BH','CUSAW1_PV_HWRES_FRNCU_WEEKBH','CUSAW1_PV_HWRES_FRNCU_PEAKBH','CUSAW1_PV_HWRES_FRNCU_TTLBH','CUSAW1_PV_HWRES_FRNCU_WTTLBH',
##                      'CUSAW1_PV_HWRES_MNC_DAY','CUSAW1_PV_HWRES_MNC_WEEK','CUSAW1_PV_HWRES_MNC_BH','CUSAW1_PV_HWRES_MNC_WEEKBH','CUSAW1_PV_HWRES_MNC_PEAKBH','CUSAW1_PV_HWRES_MNC_TTLBH','CUSAW1_PV_HWRES_MNC_WTTLBH']
##HWROFF_VIEWS_EXIST=['CUSAW1_PV_HWROFF_FWCEL_HOUR','CUSAW1_PV_HWRES_FWCEL_HOURQ','CUSAW1_PV_HWRES_FWCEL_DAY','CUSAW1_PV_HWRES_FWCEL_WEEK','CUSAW1_PV_HWRES_FWCEL_BH','CUSAW1_PV_HWRES_FWCEL_WEEKBH','CUSAW1_PV_HWRES_FWCEL_BHQ','CUSAW1_PV_HWRES_FWCEL_WKBHQ',
##                    'CUSAW1_PV_HWROFF_FRNCU_HOUR','CUSAW1_PV_HWRES_FRNCU_HOURQ','CUSAW1_PV_HWRES_FRNCU_DAY','CUSAW1_PV_HWRES_FRNCU_WEEK','CUSAW1_PV_HWRES_FRNCU_BH','CUSAW1_PV_HWRES_FRNCU_WEEKBH','CUSAW1_PV_HWRES_FRNCU_BHQ','CUSAW1_PV_HWRES_FRNCU_WKBHQ',
##                    'CUSAW1_PV_HWROFF_MNC_HOUR','CUSAW1_PV_HWRES_MNC_HOURQ','CUSAW1_PV_HWRES_MNC_DAY','CUSAW1_PV_HWRES_MNC_WEEK','CUSAW1_PV_HWRES_MNC_BH','CUSAW1_PV_HWRES_MNC_WEEKBH','CUSAW1_PV_HWRES_MNC_BHQ','CUSAW1_PV_HWRES_MNC_WKBHQ']
##HWROFF_VIEWS_NONEXIST=['CUSAW1_PV_HWROFF_FWCEL_PEAKBH','CUSAW1_PV_HWROFF_FWCEL_TTLBH','CUSAW1_PV_HWROFF_FWCEL_WTTLBH',
##                       'CUSAW1_PV_HWROFF_FRNCU_PEAKBH','CUSAW1_PV_HWROFF_FRNCU_TTLBH','CUSAW1_PV_HWROFF_FRNCU_WTTLBH',
##                       'CUSAW1_PV_HWROFF_MNC_PEAKBH','CUSAW1_PV_HWROFF_MNC_TTLBH','CUSAW1_PV_HWROFF_MNC_WTTLBH']
##HWRBH_VIEWS_EXIST=['CUSAW1_PV_HWRBH_FWCEL_HOUR','CUSAW1_PV_HWRBH_FWCEL_HOURQ','CUSAW1_PV_HWRBH_FWCEL_BHQ','CUSAW1_PV_HWRBH_FWCEL_WKBHQ',
##                   'CUSAW1_PV_HWRBH_FRNCU_HOUR','CUSAW1_PV_HWRBH_FRNCU_HOURQ','CUSAW1_PV_HWRBH_FRNCU_BHQ','CUSAW1_PV_HWRBH_FRNCU_WKBHQ',
##                   'CUSAW1_PV_HWRBH_MNC_HOUR','CUSAW1_PV_HWRBH_MNC_HOURQ','CUSAW1_PV_HWRBH_MNC_BHQ','CUSAW1_PV_HWRBH_MNC_WKBHQ']
##HWRBH_VIEWS_NONEXIST=['CUSAW1_PV_HWRBH_FWCEL_DAY','CUSAW1_PV_HWRBH_FWCEL_WEEK','CUSAW1_PV_HWRBH_FWCEL_BH','CUSAW1_PV_HWRBH_FWCEL_WEEKBH','CUSAW1_PV_HWRBH_FWCEL_PEAKBH','CUSAW1_PV_HWRBH_FWCEL_TTLBH','CUSAW1_PV_HWRBH_FWCEL_WTTLBH',
##                      'CUSAW1_PV_HWRBH_FRNCU_DAY','CUSAW1_PV_HWRBH_FRNCU_WEEK','CUSAW1_PV_HWRBH_FRNCU_BH','CUSAW1_PV_HWRBH_FRNCU_WEEKBH','CUSAW1_PV_HWRBH_FRNCU_PEAKBH','CUSAW1_PV_HWRBH_FRNCU_TTLBH','CUSAW1_PV_HWRBH_FRNCU_WTTLBH',
##                      'CUSAW1_PV_HWRBH_MNC_DAY','CUSAW1_PV_HWRBH_MNC_WEEK','CUSAW1_PV_HWRBH_MNC_BH','CUSAW1_PV_HWRBH_MNC_WEEKBH','CUSAW1_PV_HWRBH_MNC_PEAKBH','CUSAW1_PV_HWRBH_MNC_TTLBH','CUSAW1_PV_HWRBH_MNC_WTTLBH']
##HBOFF_VIEWS_EXIST=['CUSAW1_PV_HBOFF_FWCEL_HOUR','CUSAW1_PV_HBOFF_FWCEL_BH','CUSAW1_PV_HBOFF_FWCEL_WEEKBH','CUSAW1_PV_HBOFF_FWCEL_HOURQ','CUSAW1_PV_HBOFF_FWCEL_BHQ','CUSAW1_PV_HBOFF_FWCEL_WKBHQ',
##                   'CUSAW1_PV_HBOFF_FRNCU_HOUR','CUSAW1_PV_HBOFF_FRNCU_BH','CUSAW1_PV_HBOFF_FRNCU_WEEKBH','CUSAW1_PV_HBOFF_FRNCU_HOURQ','CUSAW1_PV_HBOFF_FRNCU_BHQ','CUSAW1_PV_HBOFF_FRNCU_WKBHQ',
##                   'CUSAW1_PV_HBOFF_MNC_HOUR','CUSAW1_PV_HBOFF_MNC_BH','CUSAW1_PV_HBOFF_MNC_WEEKBH','CUSAW1_PV_HBOFF_MNC_HOURQ','CUSAW1_PV_HBOFF_MNC_BHQ','CUSAW1_PV_HBOFF_MNC_WKBHQ']
##HBOFF_VIEWS_NONEXIST=['CUSAW1_PV_HBOFF_FWCEL_DAY','CUSAW1_PV_HBOFF_FWCEL_WEEK','CUSAW1_PV_HBOFF_FWCEL_PEAKBH','CUSAW1_PV_HBOFF_FWCEL_TTLBH','CUSAW1_PV_HBOFF_FWCEL_WTTLBH',
##                      'CUSAW1_PV_HBOFF_FRNCU_DAY','CUSAW1_PV_HBOFF_FRNCU_WEEK','CUSAW1_PV_HBOFF_FRNCU_PEAKBH','CUSAW1_PV_HBOFF_FRNCU_TTLBH','CUSAW1_PV_HBOFF_FRNCU_WTTLBH',
##                      'CUSAW1_PV_HBOFF_MNC_DAY','CUSAW1_PV_HBOFF_MNC_WEEK','CUSAW1_PV_HBOFF_MNC_PEAKBH','CUSAW1_PV_HBOFF_MNC_TTLBH','CUSAW1_PV_HBOFF_MNC_WTTLBH',]
##CPUT_VIEWS_EXIST=['CUSAW1_PV_CPUT_FWCEL_PEAKBH','CUSAW1_PV_CPUT_FRNCU_PEAKBH','CUSAW1_PV_CPUT_MNC_PEAKBH']
##CPUT_VIEWS_NONEXIST=['CUSAW1_PV_CPUT_FWCEL_HOUR','CUSAW1_PV_CPUT_FWCEL_HOURQ','CUSAW1_PV_CPUT_FWCEL_BHQ','CUSAW1_PV_CPUT_FWCEL_WKBHQ','CUSAW1_PV_CPUT_FWCEL_MNBHQ','CUSAW1_PV_CPUT_FWCEL_BH','CUSAW1_PV_CPUT_FWCEL_WEEKBH','CUSAW1_PV_CPUT_FWCEL_MONBH','CUSAW1_PV_CPUT_FWCEL_DAY','CUSAW1_PV_CPUT_FWCEL_WEEK','CUSAW1_PV_CPUT_FWCEL_MONTH','CUSAW1_PV_CPUT_FWCEL_TTLBH','CUSAW1_PV_CPUT_FWCEL_WTTLBH','CUSAW1_PV_CPUT_FWCEL_MTTLBH',
##                     'CUSAW1_PV_CPUT_FRNCU_HOUR','CUSAW1_PV_CPUT_FRNCU_HOURQ','CUSAW1_PV_CPUT_FRNCU_BHQ','CUSAW1_PV_CPUT_FRNCU_WKBHQ','CUSAW1_PV_CPUT_FRNCU_MNBHQ','CUSAW1_PV_CPUT_FRNCU_BH','CUSAW1_PV_CPUT_FRNCU_WEEKBH','CUSAW1_PV_CPUT_FRNCU_MONBH','CUSAW1_PV_CPUT_FRNCU_DAY','CUSAW1_PV_CPUT_FRNCU_WEEK','CUSAW1_PV_CPUT_FRNCU_MONTH','CUSAW1_PV_CPUT_FRNCU_TTLBH','CUSAW1_PV_CPUT_FRNCU_WTTLBH','CUSAW1_PV_CPUT_FRNCU_MTTLBH',
##                     'CUSAW1_PV_CPUT_MNC_HOUR','CUSAW1_PV_CPUT_MNC_HOURQ','CUSAW1_PV_CPUT_MNC_BHQ','CUSAW1_PV_CPUT_MNC_WKBHQ','CUSAW1_PV_CPUT_MNC_MNBHQ''CUSAW1_PV_CPUT_MNC_BH','CUSAW1_PV_CPUT_MNC_WEEKBH','CUSAW1_PV_CPUT_MNC_MONBH','CUSAW1_PV_CPUT_MNC_DAY','CUSAW1_PV_CPUT_MNC_WEEK','CUSAW1_PV_CPUT_MNC_MONTH','CUSAW1_PV_CPUT_MNC_TTLBH','CUSAW1_PV_CPUT_MNC_WTTLBH','CUSAW1_PV_CPUT_MNC_MTTLBH']
##CPUTBH_VIEWS_EXIST=['CUSAW1_PV_CPUTBH_FWCEL_PEAKBH','CUSAW1_PV_CPUTBH_FRNCU_PEAKBH','CUSAW1_PV_CPUTBH_MNC_PEAKBH']
##CPUTBH_VIEWS_NONEXIST=['CUSAW1_PV_CPUTBH_FWCEL_HOUR','CUSAW1_PV_CPUTBH_FWCEL_HOURQ','CUSAW1_PV_CPUTBH_FWCEL_BHQ','CUSAW1_PV_CPUTBH_FWCEL_WKBHQ','CUSAW1_PV_CPUTBH_FWCEL_MNBHQ','CUSAW1_PV_CPUTBH_FWCEL_BH','CUSAW1_PV_CPUTBH_FWCEL_WEEKBH','CUSAW1_PV_CPUTBH_FWCEL_MONBH','CUSAW1_PV_CPUTBH_FWCEL_DAY','CUSAW1_PV_CPUTBH_FWCEL_WEEK','CUSAW1_PV_CPUTBH_FWCEL_MONTH','CUSAW1_PV_CPUTBH_FWCEL_TTLBH','CUSAW1_PV_CPUTBH_FWCEL_WTTLBH','CUSAW1_PV_CPUTBH_FWCEL_MTTLBH',
##                     'CUSAW1_PV_CPUTBH_FRNCU_HOUR','CUSAW1_PV_CPUTBH_FRNCU_HOURQ','CUSAW1_PV_CPUTBH_FRNCU_BHQ','CUSAW1_PV_CPUTBH_FRNCU_WKBHQ','CUSAW1_PV_CPUTBH_FRNCU_MNBHQ','CUSAW1_PV_CPUTBH_FRNCU_BH','CUSAW1_PV_CPUTBH_FRNCU_WEEKBH','CUSAW1_PV_CPUTBH_FRNCU_MONBH','CUSAW1_PV_CPUTBH_FRNCU_DAY','CUSAW1_PV_CPUTBH_FRNCU_WEEK','CUSAW1_PV_CPUTBH_FRNCU_MONTH','CUSAW1_PV_CPUTBH_FRNCU_TTLBH','CUSAW1_PV_CPUTBH_FRNCU_WTTLBH','CUSAW1_PV_CPUTBH_FRNCU_MTTLBH',
##                     'CUSAW1_PV_CPUTBH_MNC_HOUR','CUSAW1_PV_CPUTBH_MNC_HOURQ','CUSAW1_PV_CPUTBH_MNC_BHQ','CUSAW1_PV_CPUTBH_MNC_WKBHQ','CUSAW1_PV_CPUTBH_MNC_MNBHQ''CUSAW1_PV_CPUTBH_MNC_BH','CUSAW1_PV_CPUTBH_MNC_WEEKBH','CUSAW1_PV_CPUTBH_MNC_MONBH','CUSAW1_PV_CPUTBH_MNC_DAY','CUSAW1_PV_CPUTBH_MNC_WEEK','CUSAW1_PV_CPUTBH_MNC_MONTH','CUSAW1_PV_CPUTBH_MNC_TTLBH','CUSAW1_PV_CPUTBH_MNC_WTTLBH','CUSAW1_PV_CPUTBH_MNC_MTTLBH']
##CPUTOFF_VIEWS_EXIST=['CUSAW1_PV_CPUTOFF_FWCEL_BH','CUSAW1_PV_CPUTOFF_FWCEL_WEEKBH','CUSAW1_PV_CPUTOFF_FWCEL_MONBH','CUSAW1_PV_CPUTOFF_FWCEL_DAY','CUSAW1_PV_CPUTOFF_FWCEL_WEEK','CUSAW1_PV_CPUTOFF_FWCEL_MONTH','CUSAW1_PV_CPUTOFF_FWCEL_HOUR','CUSAW1_PV_CPUTOFF_FWCEL_PEAKBH',
##                  'CUSAW1_PV_CPUTOFF_FRNCU_BH','CUSAW1_PV_CPUTOFF_FRNCU_WEEKBH','CUSAW1_PV_CPUTOFF_FRNCU_MONBH','CUSAW1_PV_CPUTOFF_FRNCU_DAY','CUSAW1_PV_CPUTOFF_FRNCU_WEEK','CUSAW1_PV_CPUTOFF_FRNCU_MONTH','CUSAW1_PV_CPUTOFF_FRNCU_HOUR','CUSAW1_PV_CPUTOFF_FRNCU_PEAKBH',
##                  'CUSAW1_PV_CPUTOFF_MNC_BH','CUSAW1_PV_CPUTOFF_MNC_WEEKBH','CUSAW1_PV_CPUTOFF_MNC_MONBH','CUSAW1_PV_CPUTOFF_MNC_DAY','CUSAW1_PV_CPUTOFF_MNC_WEEK','CUSAW1_PV_CPUTOFF_MNC_MONTH','CUSAW1_PV_CPUTOFF_MNC_HOUR','CUSAW1_PV_CPUTOFF_MNC_PEAKBH']
##CPUTOFF_VIEWS_NONEXIST=['CUSAW1_PV_CPUTOFF_FWCEL_HOURQ','CUSAW1_PV_CPUTOFF_FWCEL_BHQ','CUSAW1_PV_CPUTOFF_FWCEL_WKBHQ','CUSAW1_PV_CPUTOFF_FWCEL_MNBHQ','CUSAW1_PV_CPUTOFF_FWCEL_TTLBH','CUSAW1_PV_CPUTOFF_FWCEL_WTTLBH','CUSAW1_PV_CPUTOFF_FWCEL_MTTLBH',
##                        'CUSAW1_PV_CPUTOFF_FRNCU_HOURQ','CUSAW1_PV_CPUTOFF_FRNCU_BHQ','CUSAW1_PV_CPUTOFF_FRNCU_WKBHQ','CUSAW1_PV_CPUTOFF_FRNCU_MNBHQ','CUSAW1_PV_CPUTOFF_FRNCU_TTLBH','CUSAW1_PV_CPUTOFF_FRNCU_WTTLBH','CUSAW1_PV_CPUTOFF_FRNCU_MTTLBH',
##                        'CUSAW1_PV_CPUTOFF_MNC_HOURQ','CUSAW1_PV_CPUTOFF_MNC_BHQ','CUSAW1_PV_CPUTOFF_MNC_WKBHQ','CUSAW1_PV_CPUTOFF_MNC_MNBHQ','CUSAW1_PV_CPUTOFF_MNC_TTLBH','CUSAW1_PV_CPUTOFF_MNC_WTTLBH','CUSAW1_PV_CPUTOFF_MNC_MTTLBH']
##CBOFF_VIEWS_EXIST=['CUSAW1_PV_CBOFF_FWCEL_BH','CUSAW1_PV_CPUTBH_FWCEL_WEEKBH','CUSAW1_PV_CPUTBH_FWCEL_MONBH','CUSAW1_PV_CPUTBH_FWCEL_PEAKBH',
##                   'CUSAW1_PV_CBOFF_FRNCU_BH','CUSAW1_PV_CPUTBH_FRNCU_WEEKBH','CUSAW1_PV_CPUTBH_FRNCU_MONBH','CUSAW1_PV_CPUTBH_FRNCU_PEAKBH',
##                   'CUSAW1_PV_CBOFF_MNC_BH','CUSAW1_PV_CPUTBH_MNC_WEEKBH','CUSAW1_PV_CPUTBH_MNC_MONBH','CUSAW1_PV_CPUTBH_MNC_PEAKBH']
##CBOFF_VIEWS_NONEXIST=['CUSAW1_PV_CBOFF_FWCEL_HOUR','CUSAW1_PV_CBOFF_FWCEL_DAY','CUSAW1_PV_CBOFF_FWCEL_WEEK','CUSAW1_PV_CBOFF_FWCEL_MONTH','CUSAW1_PV_CBOFF_FWCEL_HOURQ','CUSAW1_PV_CBOFF_FWCEL_BHQ','CUSAW1_PV_CBOFF_FWCEL_WKBHQ','CUSAW1_PV_CBOFF_FWCEL_MNBHQ','CUSAW1_PV_CBOFF_FWCEL_TTLBH','CUSAW1_PV_CBOFF_FWCEL_WTTLBH','CUSAW1_PV_CBOFF_FWCEL_MTTLBH',
##                      'CUSAW1_PV_CBOFF_FRNCU_HOUR','CUSAW1_PV_CBOFF_FRNCU_DAY','CUSAW1_PV_CBOFF_FRNCU_WEEK','CUSAW1_PV_CBOFF_FRNCU_MONTH','CUSAW1_PV_CBOFF_FRNCU_HOURQ','CUSAW1_PV_CBOFF_FRNCU_BHQ','CUSAW1_PV_CBOFF_FRNCU_WKBHQ','CUSAW1_PV_CBOFF_FRNCU_MNBHQ','CUSAW1_PV_CBOFF_FRNCU_TTLBH','CUSAW1_PV_CBOFF_FRNCU_WTTLBH','CUSAW1_PV_CBOFF_FRNCU_MTTLBH',
##                      'CUSAW1_PV_CBOFF_MNC_HOUR','CUSAW1_PV_CBOFF_MNC_DAY','CUSAW1_PV_CBOFF_MNC_WEEK','CUSAW1_PV_CBOFF_MNC_MONTH','CUSAW1_PV_CBOFF_MNC_HOURQ','CUSAW1_PV_CBOFF_MNC_BHQ','CUSAW1_PV_CBOFF_MNC_WKBHQ','CUSAW1_PV_CBOFF_MNC_MNBHQ','CUSAW1_PV_CBOFF_MNC_TTLBH','CUSAW1_PV_CBOFF_MNC_WTTLBH','CUSAW1_PV_CBOFF_MNC_MTTLBH']
##FANS_VIEWS_EXIST=['CUSAW1_PV_FANS_FWCEL_BH','CUSAW1_PV_FANS_FWCEL_WEEKBH','CUSAW1_PV_FANS_FWCEL_TTLBH','CUSAW1_PV_FANS_FWCEL_WTTLBH',
##                  'CUSAW1_PV_FANS_FRNCU_BH','CUSAW1_PV_FANS_FRNCU_WEEKBH','CUSAW1_PV_FANS_FRNCU_TTLBH','CUSAW1_PV_FANS_FRNCU_WTTLBH',
##                  'CUSAW1_PV_FANS_MNC_BH','CUSAW1_PV_FANS_MNC_WEEKBH','CUSAW1_PV_FANS_MNC_TTLBH','CUSAW1_PV_FANS_MNC_WTTLBH']
##FANS_VIEWS_NONEXIST=['CUSAW1_PV_FANS_FWCEL_HOUR','CUSAW1_PV_FANS_FWCEL_DAY','CUSAW1_PV_FANS_FWCEL_WEEK','CUSAW1_PV_FANS_FWCEL_HOURQ','CUSAW1_PV_FANS_FWCEL_BHQ','CUSAW1_PV_FANS_FWCEL_WKBHQ','CUSAW1_PV_FANS_FWCEL_PEAKBH',
##                     'CUSAW1_PV_FANS_FRNCU_HOUR','CUSAW1_PV_FANS_FRNCU_DAY','CUSAW1_PV_FANS_FRNCU_WEEK','CUSAW1_PV_FANS_FRNCU_HOURQ','CUSAW1_PV_FANS_FRNCU_BHQ','CUSAW1_PV_FANS_FRNCU_WKBHQ','CUSAW1_PV_FANS_FRNCU_PEAKBH',
##                     'CUSAW1_PV_FANS_MNC_HOUR','CUSAW1_PV_FANS_MNC_DAY','CUSAW1_PV_FANS_MNC_WEEK','CUSAW1_PV_FANS_MNC_HOURQ','CUSAW1_PV_FANS_MNC_BHQ','CUSAW1_PV_FANS_MNC_WKBHQ','CUSAW1_PV_FANS_MNC_PEAKBH']
##FANSOFF_VIEWS_EXIST=['CUSAW1_PV_FANSOFF_FWCEL_BH','CUSAW1_PV_FANSOFF_FWCEL_WEEKBH','CUSAW1_PV_FANSOFF_FWCEL_TTLBH','CUSAW1_PV_FANSOFF_FWCEL_WTTLBH',
##                     'CUSAW1_PV_FANSOFF_FRNCU_BH','CUSAW1_PV_FANSOFF_FRNCU_WEEKBH','CUSAW1_PV_FANSOFF_FRNCU_TTLBH','CUSAW1_PV_FANSOFF_FRNCU_WTTLBH',
##                     'CUSAW1_PV_FANSOFF_MNC_BH','CUSAW1_PV_FANSOFF_MNC_WEEKBH','CUSAW1_PV_FANSOFF_MNC_TTLBH','CUSAW1_PV_FANSOFF_MNC_WTTLBH']
##FANSOFF_VIEWS_NONEXIST=['CUSAW1_PV_FANSOFF_FWCEL_HOUR','CUSAW1_PV_FANSOFF_FWCEL_DAY','CUSAW1_PV_FANSOFF_FWCEL_WEEK','CUSAW1_PV_FANSOFF_FWCEL_PEAKBH','CUSAW1_PV_FANSOFF_FWCEL_HOURQ','CUSAW1_PV_FANSOFF_FWCEL_BHQ','CUSAW1_PV_FANSOFF_FWCEL_WKBHQ',
##                        'CUSAW1_PV_FANSOFF_FRNCU_HOUR','CUSAW1_PV_FANSOFF_FRNCU_DAY','CUSAW1_PV_FANSOFF_FRNCU_WEEK','CUSAW1_PV_FANSOFF_FRNCU_PEAKBH','CUSAW1_PV_FANSOFF_FRNCU_HOURQ','CUSAW1_PV_FANSOFF_FRNCU_BHQ','CUSAW1_PV_FANSOFF_FRNCU_WKBHQ',
##                        'CUSAW1_PV_FANSOFF_MNC_HOUR','CUSAW1_PV_FANSOFF_MNC_DAY','CUSAW1_PV_FANSOFF_MNC_WEEK','CUSAW1_PV_FANSOFF_MNC_PEAKBH','CUSAW1_PV_FANSOFF_MNC_HOURQ','CUSAW1_PV_FANSOFF_MNC_BHQ','CUSAW1_PV_FANSOFF_MNC_WKBHQ']
##FANS3_VIEWS_EXIST=['CUSAW1_PV_FANS3_FWCEL_HOUR','CUSAW1_PV_FANS3_FWCEL_DAY','CUSAW1_PV_FANS3_FWCEL_WEEK','CUSAW1_PV_FANS3_FWCEL_BH','CUSAW1_PV_FANS3_FWCEL_WEEKBH',
##                   'CUSAW1_PV_FANS3_FRNCU_HOUR','CUSAW1_PV_FANS3_FRNCU_DAY','CUSAW1_PV_FANS3_FRNCU_WEEK','CUSAW1_PV_FANS3_FRNCU_BH','CUSAW1_PV_FANS3_FRNCU_WEEKBH',
##                   'CUSAW1_PV_FANS3_MNC_HOUR','CUSAW1_PV_FANS3_MNC_DAY','CUSAW1_PV_FANS3_MNC_WEEK','CUSAW1_PV_FANS3_MNC_BH','CUSAW1_PV_FANS3_MNC_WEEKBH']
##FANS3_VIEWS_NONEXIST=['CUSAW1_PV_FANS3_FWCEL_HOURQ','CUSAW1_PV_FANS3_FWCEL_BHQ','CUSAW1_PV_FANS3_FWCEL_WKBHQ','CUSAW1_PV_FANS3_FWCEL_PEAKBH','CUSAW1_PV_FANS3_FWCEL_TTLBH','CUSAW1_PV_FANS3_FWCEL_WTTLBH',
##                      'CUSAW1_PV_FANS3_FRNCU_HOURQ','CUSAW1_PV_FANS3_FRNCU_BHQ','CUSAW1_PV_FANS3_FRNCU_WKBHQ','CUSAW1_PV_FANS3_FRNCU_PEAKBH','CUSAW1_PV_FANS3_FRNCU_TTLBH','CUSAW1_PV_FANS3_FRNCU_WTTLBH',
##                      'CUSAW1_PV_FANS3_MNC_HOURQ','CUSAW1_PV_FANS3_MNC_BHQ','CUSAW1_PV_FANS3_MNC_WKBHQ','CUSAW1_PV_FANS3_MNC_PEAKBH','CUSAW1_PV_FANS3_MNC_TTLBH','CUSAW1_PV_FANS3_MNC_WTTLBH']
##FANS4_VIEWS_EXIST=['CUSAW1_PV_FANS4_FWCEL_BH','CUSAW1_PV_FANS4_FWCEL_WEEKBH',
##                   'CUSAW1_PV_FANS4_FRNCU_BH','CUSAW1_PV_FANS4_FRNCU_WEEKBH',
##                   'CUSAW1_PV_FANS4_MNC_BH','CUSAW1_PV_FANS4_MNC_WEEKBH']
##FANS4_VIEWS_NONEXIST=['CUSAW1_PV_FANS4_FWCEL_HOUR','CUSAW1_PV_FANS4_FWCEL_DAY','CUSAW1_PV_FANS4_FWCEL_WEEK','CUSAW1_PV_FANS4_FWCEL_HOURQ','CUSAW1_PV_FANS4_FWCEL_BHQ','CUSAW1_PV_FANS4_FWCEL_WKBHQ','CUSAW1_PV_FANS4_FWCEL_PEAKBH','CUSAW1_PV_FANS4_FWCEL_TTLBH','CUSAW1_PV_FANS4_FWCEL_WTTLBH',
##                      'CUSAW1_PV_FANS4_FRNCU_HOUR','CUSAW1_PV_FANS4_FRNCU_DAY','CUSAW1_PV_FANS4_FRNCU_WEEK','CUSAW1_PV_FANS4_FRNCU_HOURQ','CUSAW1_PV_FANS4_FRNCU_BHQ','CUSAW1_PV_FANS4_FRNCU_WKBHQ','CUSAW1_PV_FANS4_FRNCU_PEAKBH','CUSAW1_PV_FANS4_FRNCU_TTLBH','CUSAW1_PV_FANS4_FRNCU_WTTLBH',
##                      'CUSAW1_PV_FANS4_MNC_HOUR','CUSAW1_PV_FANS4_MNC_DAY','CUSAW1_PV_FANS4_MNC_WEEK','CUSAW1_PV_FANS4_MNC_HOURQ','CUSAW1_PV_FANS4_MNC_BHQ','CUSAW1_PV_FANS4_MNC_WKBHQ','CUSAW1_PV_FANS4_MNC_PEAKBH','CUSAW1_PV_FANS4_MNC_TTLBH','CUSAW1_PV_FANS4_MNC_WTTLBH']
##FANS5_VIEWS_EXIST=['CUSAW1_PV_FANS5_FWCEL_HOUR','CUSAW1_PV_FANS5_FWCEL_DAY','CUSAW1_PV_FANS5_FWCEL_WEEK','CUSAW1_PV_FANS5_FWCEL_BH','CUSAW1_PV_FANS5_FWCEL_WEEKBH',
##                   'CUSAW1_PV_FANS5_FRNCU_HOUR','CUSAW1_PV_FANS5_FRNCU_DAY','CUSAW1_PV_FANS5_FRNCU_WEEK','CUSAW1_PV_FANS5_FRNCU_BH','CUSAW1_PV_FANS5_FRNCU_WEEKBH',
##                   'CUSAW1_PV_FANS5_MNC_HOUR','CUSAW1_PV_FANS5_MNC_DAY','CUSAW1_PV_FANS5_MNC_WEEK','CUSAW1_PV_FANS5_MNC_BH','CUSAW1_PV_FANS5_MNC_WEEKBH']
##FANS5_VIEWS_NONEXIST=['CUSAW1_PV_FANS5_FWCEL_HOURQ','CUSAW1_PV_FANS5_FWCEL_BHQ','CUSAW1_PV_FANS5_FWCEL_WKBHQ','CUSAW1_PV_FANS5_FWCEL_PEAKBH','CUSAW1_PV_FANS5_FWCEL_TTLBH','CUSAW1_PV_FANS5_FWCEL_WTTLBH',
##                      'CUSAW1_PV_FANS5_FRNCU_HOURQ','CUSAW1_PV_FANS5_FRNCU_BHQ','CUSAW1_PV_FANS5_FRNCU_WKBHQ','CUSAW1_PV_FANS5_FRNCU_PEAKBH','CUSAW1_PV_FANS5_FRNCU_TTLBH','CUSAW1_PV_FANS5_FRNCU_WTTLBH',
##                      'CUSAW1_PV_FANS5_MNC_HOURQ','CUSAW1_PV_FANS5_MNC_BHQ','CUSAW1_PV_FANS5_MNC_WKBHQ','CUSAW1_PV_FANS5_MNC_PEAKBH','CUSAW1_PV_FANS5_MNC_TTLBH','CUSAW1_PV_FANS5_MNC_WTTLBH']
##FANS6_VIEWS_EXIST=['CUSAW1_PV_FANS6_FWCEL_BH','CUSAW1_PV_FANS6_FWCEL_WEEKBH',
##                   'CUSAW1_PV_FANS6_FRNCU_BH','CUSAW1_PV_FANS6_FRNCU_WEEKBH',
##                   'CUSAW1_PV_FANS6_MNC_BH','CUSAW1_PV_FANS6_MNC_WEEKBH']
##FANS6_VIEWS_NONEXIST=['CUSAW1_PV_FANS6_FWCEL_HOUR','CUSAW1_PV_FANS6_FWCEL_DAY','CUSAW1_PV_FANS6_FWCEL_WEEK','CUSAW1_PV_FANS6_FWCEL_HOURQ','CUSAW1_PV_FANS6_FWCEL_BHQ','CUSAW1_PV_FANS6_FWCEL_WKBHQ','CUSAW1_PV_FANS6_FWCEL_PEAKBH','CUSAW1_PV_FANS6_FWCEL_TTLBH','CUSAW1_PV_FANS6_FWCEL_WTTLBH',
##                      'CUSAW1_PV_FANS6_FRNCU_HOUR','CUSAW1_PV_FANS6_FRNCU_DAY','CUSAW1_PV_FANS6_FRNCU_WEEK','CUSAW1_PV_FANS6_FRNCU_HOURQ','CUSAW1_PV_FANS6_FRNCU_BHQ','CUSAW1_PV_FANS6_FRNCU_WKBHQ','CUSAW1_PV_FANS6_FRNCU_PEAKBH','CUSAW1_PV_FANS6_FRNCU_TTLBH','CUSAW1_PV_FANS6_FRNCU_WTTLBH',
##                      'CUSAW1_PV_FANS6_MNC_HOUR','CUSAW1_PV_FANS6_MNC_DAY','CUSAW1_PV_FANS6_MNC_WEEK','CUSAW1_PV_FANS6_MNC_HOURQ','CUSAW1_PV_FANS6_MNC_BHQ','CUSAW1_PV_FANS6_MNC_WKBHQ','CUSAW1_PV_FANS6_MNC_PEAKBH','CUSAW1_PV_FANS6_MNC_TTLBH','CUSAW1_PV_FANS6_MNC_WTTLBH']















